name: Build
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk, 18-jdk]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew build javadocJar checkMappings --stacktrace --warning-mode fail
      - name: Build artifacts
        if: ${{ matrix.java == '18-jdk' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - name: Generate build number
        if: ${{ matrix.java == '18-jdk' }}
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}
      - name: Publish release
        if: ${{ matrix.java == '18-jdk' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: '${{ github.ref_name }}.build.${{ github.run_number }}'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          files: build/libs/*.jar

  test-build-logic:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew :filament:build